name: Create draft release

on:
  push:
    tags:
      - '*/v*'

jobs:
  create-draft-release:
    runs-on: ubuntu-latest

    steps:
      # ref. https://github.com/orgs/community/discussions/26686
      - name: GitHub Tag Name example
        run: |
          echo "Target tag name: ${{  github.ref_name }}"
