name: Create draft release

on:
  # GitHub Acrtions経由のタグプッシュでは`tags`がトリガーされないので、ワークフロートリガーにする
  # ref. https://www.memory-lovers.blog/entry/2022/11/20/180000
  workflow_run:
    workflows:
      - Push tag
    types:
      - completed

jobs:
  create-draft-release:
    # イベント情報の詳細はJSONペイロード出力している以下の記事を見ると分かりやすい
    # ref. https://swfz.hatenablog.com/entry/2022/04/24/183151
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # ref. https://github.com/marketplace/actions/split-action
      - uses: jungwinter/split@v2
        id: split
        with:
          msg: ${{  github.event.workflow_run.head_branch }}
          separator: '/'

      # ワークフローAのアーティファクトからタグを取得する手順
      - name: Download tag artifact
        uses: actions/download-artifact@v3
        with:
          name: tag-artifact

      # ダウンロードしたタグを表示する手順
      - name: Display tag
        run: cat /tmp/tag_name.txt

      # ref. https://github.com/orgs/community/discussions/26686
      - name: Get the tag name
        id: tag-name
        run: |
          echo "Target tag name: ${{  github.event.workflow_run.head_branch }}"
          echo "target=${{ steps.split.outputs._0 }}" >> $GITHUB_OUTPUT
          echo "version=${{ steps.split.outputs._1 }}" >> $GITHUB_OUTPUT

      - name: Extract the specific version CHANGELOG
        id: changelog
        # GITHUB_OUTPUTやGITHUB_ENVでは改行が扱えないので、一旦ファイルに書き出す
        run: |
          mkdir -p /tmp
          ($echo ./.github/script/extract_specific_changelog.sh \
              --target=${{ steps.tag-name.outputs.target }} \
              --version=${{ steps.tag-name.outputs.version }}) \
            > /tmp/body.md

      - name: Show CHANGELOG
        run: |
          cat /tmp/body.md

      # ref. https://github.com/ncipollo/release-action
      - name: Create draft release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{  github.event.workflow_run.head_branch }}
          bodyFile: /tmp/body.md
          generateReleaseNotes: true
          draft: true
          prerelease: false
