name: Create draft release

on:
  push:
    tags:
      - '*/v*'

jobs:
  create-draft-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # ref. https://github.com/marketplace/actions/split-action
      - uses: jungwinter/split@v2
        id: split
        with:
          msg: ${{  github.ref_name }}
          separator: '/'

      # ref. https://github.com/orgs/community/discussions/26686
      - name: Get the tag name
        id: tag-name
        run: |
          echo "Target tag name: ${{  github.ref_name }}"
          echo "target=${{ steps.split.outputs._0 }}" >> $GITHUB_OUTPUT
          echo "version=${{ steps.split.outputs._1 }}" >> $GITHUB_OUTPUT

      - name: Extract the specific version CHANGELOG
        id: changelog
        # GITHUB_OUTPUTやGITHUB_ENVでは改行が扱えないので、一旦ファイルに書き出す
        run: |
          mkdir -p /tmp
          ($echo ./.github/script/extract_specific_changelog.sh \
              --target=${{ steps.tag-name.outputs.target }} \
              --version=${{ steps.tag-name.outputs.version }}) \
            > /tmp/body.md

      - name: Show CHANGELOG
        run: |
          cat /tmp/body.md

      # ref. https://github.com/ncipollo/release-action
      - name: Create draft release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{  github.ref_name }}
          bodyFile: /tmp/body.md
          generateReleaseNotes: true
          draft: true
          prerelease: false
