name: Push tag

on:
  workflow_dispatch:
    inputs:
      extension:
        type: choice
        options:
          - 'back-up-firestore-to-storage'
          - 'trigger-github-issues-from-crashlytics'
        required: true
        description: 'The name of the extension'
      version:
        type: string
        required: true
        description: 'The version of the extension'
      commit:
        type: string
        required: false
        description: 'Target the commit id (Defaults to HEAD)'

jobs:
  push-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      TAG_NAME: ${{ github.event.inputs.extension }}/v${{ github.event.inputs.version }}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.commit }}

      - name: Push tag
        run: |
          git tag $TAG_NAME
          git push origin $TAG_NAME
