name: Push tag

on:
  workflow_dispatch:
    inputs:
      extension:
        type: choice
        options:
          - 'back-up-firestore-to-storage'
          - 'trigger-github-issues-from-crashlytics'
        required: true
        description: 'The name of the extension'
      version:
        type: string
        required: true
        description: 'The version of the extension'
      commit:
        type: string
        required: false
        description: 'Target the commit id (Defaults to HEAD)'

jobs:
  push-tag:
    runs-on: ubuntu-latest
    env:
      TAG_NAME: ${{ github.event.inputs.extension }}/v${{ github.event.inputs.version }}
      ARTIFACT_FILE: /tmp/tag.txt

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.commit }}

      - name: Push tag
        run: |
          git tag $TAG_NAME
          git push origin $TAG_NAME

      - name: Output tag
        run: |
          mkdir -p tmp
          echo $TAG_NAME > $ARTIFACT_FILE
          cat $ARTIFACT_FILE

      - name: Upload tag name as artifact
        uses: actions/upload-artifact@v3
        with:
          name: tag-artifact
          # ここでは環境変数の参照はできないのでベタ指定
          path: /tmp/tag.txt
