name: Release

on:
  workflow_dispatch:
    inputs:
      extension:
        type: choice
        options:
          - 'back-up-firestore-to-storage'
          - 'trigger-github-issues-from-crashlytics'
        required: true
        description: 'The name of the extension'
      version:
        type: string
        required: true
        description: 'The version of the extension'
      commit:
        type: string
        required: false
        description: 'Target the commit id (Defaults to HEAD)'

env:
  TAG_NAME: ${{ github.event.inputs.extension }}/v${{ github.event.inputs.version }}

jobs:
  push-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.commit }}

      - name: Push tag
        run: |
          git tag $TAG_NAME
          git push origin $TAG_NAME

  create-draft-release:
    needs: push-tag
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # ref. https://github.com/marketplace/actions/split-action
      - uses: jungwinter/split@v2
        id: split
        with:
          msg: ${{ env.TAG_NAME }}
          separator: '/'

      # ref. https://github.com/orgs/community/discussions/26686
      - name: Get the tag name
        id: tag-name
        run: |
          echo "Target tag name: ${{ env.TAG_NAME }}"
          echo "target=${{ steps.split.outputs._0 }}" >> $GITHUB_OUTPUT
          echo "version=${{ steps.split.outputs._1 }}" >> $GITHUB_OUTPUT

      - name: Extract the specific version CHANGELOG
        id: changelog
        # GITHUB_OUTPUTやGITHUB_ENVでは改行が扱えないので、一旦ファイルに書き出す
        run: |
          mkdir -p /tmp
          ($echo ./.github/script/extract_specific_changelog.sh \
              --target=${{ steps.tag-name.outputs.target }} \
              --version=${{ steps.tag-name.outputs.version }}) \
            > /tmp/body.md

      - name: Show CHANGELOG
        run: |
          cat /tmp/body.md

      # ref. https://github.com/ncipollo/release-action
      - name: Create draft release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.TAG_NAME }}
          bodyFile: /tmp/body.md
          generateReleaseNotes: true
          draft: true
          prerelease: false
